event_inherited();
spd = 2;
dir = 1;
state = "idle";
preAttack = false;
hp = 1;
grav = 0.2;
jSpd = 2;
moveZ = 0;
hasPlayedAttackSound = false;
hasPlayedHitSound = false;
canDust = true;
dustTime = 0.5;
fall = false;
hasDied = false;